import type { Gender, UserRole, WorkModel } from "@prisma/client";

export type SeedOrganization = {
  id: string;
  name: string;
  domain: string;
  timezone: string;
  locale: string;
};

export type SeedTeam = {
  id: string;
  name: string;
  description: string;
};

export type SeedUserConfig = {
  id: string;
  organizationId: string;
  email: string;
  password: string;
  role: UserRole;
  firstName: string;
  lastName: string;
  preferredName: string;
  designation: string;
  employeeCode: string;
  teamId?: string | null;
  workModel?: WorkModel;
  workPhone?: string | null;
  personalPhone?: string | null;
  reportingManagerId?: string | null;
  gender?: Gender;
};

export const organizations: SeedOrganization[] = [
  {
    id: "1",
    name: "Ninja Digital Innovations",
    domain: "ninja-digital-innovations.com",
    timezone: "Asia/Dhaka",
    locale: "en-US",
  },
  {
    id: "2",
    name: "Brand Cloud",
    domain: "brandcloud.com",
    timezone: "Asia/Tokyo",
    locale: "en-US",
  },
];

export const organizationNameById = organizations.reduce<Record<string, string>>((acc, org) => {
  acc[org.id] = org.name;
  return acc;
}, {});

export const orgTeams: Record<string, SeedTeam[]> = {
  "1": [
    {
      id: "1",
      name: "Management",
      description: "Executive leadership and strategic oversight.",
    },
    {
      id: "2",
      name: "Frontend",
      description: "Client-facing applications and UI delivery.",
    },
    {
      id: "3",
      name: "Backend",
      description: "API, integrations, and data services.",
    },
    {
      id: "4",
      name: "Design",
      description: "Product design and research.",
    },
    {
      id: "5",
      name: "SNS",
      description: "Communications and social media initiatives.",
    },
  ],
  "2": [
    {
      id: "6",
      name: "Management",
      description: "Brand Cloud leadership and strategy.",
    },
    {
      id: "7",
      name: "Frontend",
      description: "Marketing site delivery and client portals.",
    },
    {
      id: "8",
      name: "Backend",
      description: "Platform integrations and core services.",
    },
    {
      id: "9",
      name: "Design",
      description: "Creative direction and visual systems.",
    },
    {
      id: "10",
      name: "SNS",
      description: "Social engagement and campaigns.",
    },
  ],
};

export const usersToCreate: SeedUserConfig[] = [
  {
    id: "superuser",
    organizationId: "1",
    email: "superuser@ninja-digital-innovations.com",
    password: "Superuser@123",
    role: "SUPER_ADMIN",
    firstName: "Superuser",
    lastName: "Admin",
    preferredName: "Superuser",
    designation: "Chief Administrator",
    employeeCode: "NDI-SUPER",
    teamId: "1",
    workModel: "HYBRID",
    workPhone: "+8801300001101",
    personalPhone: "+8801700001101",
    reportingManagerId: null,
  },
  {
    id: "0001",
    organizationId: "1",
    email: "sufi.aurangzeb.hossain@ninja-digital-innovations.com",
    password: "Ndi@0001",
    role: "MANAGER",
    firstName: "Sufi Aurangzeb",
    lastName: "Hossain",
    preferredName: "Sufi",
    designation: "Software Engineer",
    employeeCode: "NDI-0001",
    teamId: "3",
    workModel: "ONSITE",
    workPhone: "+8801521466157",
    personalPhone: null,
    reportingManagerId: null,
    gender: "MALE",
  },
  {
    id: "0003",
    organizationId: "1",
    email: "hazrat.ali2@ninja-digital-innovations.com",
    password: "Ndi@0003",
    role: "MANAGER",
    firstName: "Md Hazrat",
    lastName: "Ali",
    preferredName: "Hazrat",
    designation: "Software Engineer",
    employeeCode: "NDI-0003",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801306440448",
    personalPhone: null,
    reportingManagerId: null,
    gender: "MALE",
  },
  {
    id: "0005",
    organizationId: "1",
    email: "zahidul.islam@ninja-digital-innovations.com",
    password: "Ndi@0005",
    role: "EMPLOYEE",
    firstName: "Md. Zahidul",
    lastName: "Islam",
    preferredName: "Zahidul",
    designation: "Software Engineer",
    employeeCode: "NDI-0005",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801754898514",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0009",
    organizationId: "1",
    email: "tahmina.akter@ninja-digital-innovations.com",
    password: "Ndi@0009",
    role: "MANAGER",
    firstName: "Tahmina",
    lastName: "Akter",
    preferredName: "Tahmina",
    designation: "Designer",
    employeeCode: "NDI-0009",
    teamId: "4",
    workModel: "ONSITE",
    workPhone: "+8801817612252",
    personalPhone: null,
    reportingManagerId: null,
    gender: "FEMALE",
  },
  {
    id: "0012",
    organizationId: "1",
    email: "mustahid.hasan@ninja-digital-innovations.com",
    password: "Ndi@0012",
    role: "EMPLOYEE",
    firstName: "Mustahid",
    lastName: "Hasan",
    preferredName: "Mustahid",
    designation: "Software Engineer",
    employeeCode: "NDI-0012",
    teamId: "3",
    workModel: "ONSITE",
    workPhone: "+8801754627430",
    personalPhone: null,
    reportingManagerId: "0001",
    gender: "MALE",
  },
  {
    id: "0014",
    organizationId: "1",
    email: "arpon.hasan@ninja-digital-innovations.com",
    password: "Ndi@0014",
    role: "HR_ADMIN",
    firstName: "Mohammad Arpon",
    lastName: "Hasan",
    preferredName: "Arpon",
    designation: "HR Officer",
    employeeCode: "NDI-0014",
    teamId: "1",
    workModel: "ONSITE",
    workPhone: "+8801303241326",
    personalPhone: null,
    reportingManagerId: "0099",
    gender: "MALE",
  },
  {
    id: "0016",
    organizationId: "1",
    email: "saiful.islam.rifat@ninja-digital-innovations.com",
    password: "Ndi@0016",
    role: "EMPLOYEE",
    firstName: "Saiful Islam",
    lastName: "Rifat",
    preferredName: "Rifat",
    designation: "Software Engineer",
    employeeCode: "NDI-0016",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801718440266",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0018",
    organizationId: "1",
    email: "omar.shahariar@ninja-digital-innovations.com",
    password: "Ndi@0018",
    role: "EMPLOYEE",
    firstName: "Md. Omar",
    lastName: "Shahariar",
    preferredName: "Omar",
    designation: "Software Engineer",
    employeeCode: "NDI-0018",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801622630550",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0021",
    organizationId: "1",
    email: "sohel.rana@ninja-digital-innovations.com",
    password: "Ndi@0021",
    role: "EMPLOYEE",
    firstName: "Md. Sohel",
    lastName: "Rana",
    preferredName: "Sohel",
    designation: "Software Engineer",
    employeeCode: "NDI-0021",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801825979759",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0029",
    organizationId: "1",
    email: "sourov.mia@ninja-digital-innovations.com",
    password: "Ndi@0029",
    role: "EMPLOYEE",
    firstName: "Md. Sourov",
    lastName: "Mia",
    preferredName: "Sourov",
    designation: "Software Engineer",
    employeeCode: "NDI-0029",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801605700926",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0030",
    organizationId: "1",
    email: "sunny.sutradhar@ninja-digital-innovations.com",
    password: "Ndi@0030",
    role: "EMPLOYEE",
    firstName: "Sunny",
    lastName: "Sutradhar",
    preferredName: "Sunny",
    designation: "Software Engineer",
    employeeCode: "NDI-0030",
    teamId: "3",
    workModel: "ONSITE",
    workPhone: "+8801580349348",
    personalPhone: null,
    reportingManagerId: "0001",
    gender: "MALE",
  },
  {
    id: "0032",
    organizationId: "1",
    email: "mueem.nahid@ninja-digital-innovations.com",
    password: "Ndi@0032",
    role: "EMPLOYEE",
    firstName: "Mueem Nahid Ibn",
    lastName: "Mahbub",
    preferredName: "Mueem",
    designation: "Software Engineer",
    employeeCode: "NDI-0032",
    teamId: "2",
    workModel: "REMOTE",
    workPhone: "+8801408454475",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0033",
    organizationId: "1",
    email: "rafidul.islam@ninja-digital-innovations.com",
    password: "Ndi@0033",
    role: "EMPLOYEE",
    firstName: "Md. Rafidul",
    lastName: "Islam",
    preferredName: "Rafidul",
    designation: "Software Engineer",
    employeeCode: "NDI-0033",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801850700054",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0035",
    organizationId: "1",
    email: "masud.rana@ninja-digital-innovations.com",
    password: "Ndi@0035",
    role: "EMPLOYEE",
    firstName: "Masud",
    lastName: "Rana",
    preferredName: "Masud",
    designation: "Designer",
    employeeCode: "NDI-0035",
    teamId: "4",
    workModel: "ONSITE",
    workPhone: "+8801993590550",
    personalPhone: null,
    reportingManagerId: "0009",
    gender: "MALE",
  },
  {
    id: "0046",
    organizationId: "1",
    email: "yeasir.arafat@ninja-digital-innovations.com",
    password: "Ndi@0046",
    role: "HR_ADMIN",
    firstName: "Md. Yeasir",
    lastName: "Arafat",
    preferredName: "Yeasir",
    designation: "HR Executive",
    employeeCode: "NDI-0046",
    teamId: "2",
    workModel: "ONSITE",
    workPhone: "+8801725449862",
    personalPhone: null,
    reportingManagerId: "0003",
    gender: "MALE",
  },
  {
    id: "0099",
    organizationId: "1",
    email: "satoru.tabuchi@ninja-digital-innovations.com",
    password: "Ndi@0099",
    role: "ORG_ADMIN",
    firstName: "Satoru",
    lastName: "Tabuchi",
    preferredName: "Satoru",
    designation: "General Manager",
    employeeCode: "NDI-0099",
    teamId: "1",
    workModel: "ONSITE",
    workPhone: "+8801805118756",
    personalPhone: null,
    reportingManagerId: null,
    gender: "MALE",
  },
];
