import { PrismaClient, type UserRole } from "@prisma/client";

import { NDI_ORG_ID } from "./data";

const notifications = [
  {
    id: "notif-announcement-remote",
    organizationId: NDI_ORG_ID,
    senderId: "org-manager-tabuchi",
    title: "December 4: remote work for on-site teams",
    body: "All on-site squads will work remotely on Thursday, December 4 due to the building maintenance drill.",
    type: "ANNOUNCEMENT" as const,
    audience: "ROLE" as const,
    targetRoles: ["EMPLOYEE"] as UserRole[],
    status: "SENT" as const,
    actionUrl: "/announcements/dec-remote-shift",
    metadata: {
      reason: "Fire safety drill",
      appliesTo: "ONSITE",
      effectiveDate: "2025-12-04",
    },
    sentAt: new Date("2025-01-10T08:00:00+06:00"),
  },
  {
    id: "notif-announcement-holiday",
    organizationId: NDI_ORG_ID,
    senderId: "org-admin-kohei",
    title: "Victory Day office closure",
    body: "The Dhaka HQ will be closed on December 16 for Victory Day. Enjoy the long weekend!",
    type: "ANNOUNCEMENT" as const,
    audience: "ORGANIZATION" as const,
    status: "SENT" as const,
    actionUrl: "/calendar/holiday/victory-day",
    metadata: {
      holidayDate: "2025-12-16",
      region: "BD",
    },
    sentAt: new Date("2025-01-09T09:00:00+06:00"),
  },
  {
    id: "notif-leave-pending",
    organizationId: NDI_ORG_ID,
    senderId: "frontend-lead-hazrat",
    title: "Leave approval needed: Saiful (Jan 15)",
    body: "Saiful requested casual leave for January 15. Please review before EOD.",
    type: "LEAVE" as const,
    audience: "ROLE" as const,
    targetRoles: ["HR_ADMIN"] as UserRole[],
    status: "SENT" as const,
    actionUrl: "/hr-admin/leave/leave-2",
    metadata: {
      leaveRequestId: "leave-2",
      employeeId: "emp-saiful",
      leaveType: "CASUAL",
      dates: {
        start: "2025-01-15",
        end: "2025-01-15",
      },
    },
    sentAt: new Date("2025-01-10T10:00:00+06:00"),
  },
  {
    id: "notif-leave-approved",
    organizationId: NDI_ORG_ID,
    senderId: "hr-yeasir",
    title: "Your leave was approved",
    body: "Great news! Your casual leave request for January 15 has been approved.",
    type: "LEAVE" as const,
    audience: "INDIVIDUAL" as const,
    targetUserId: "emp-saiful",
    status: "SENT" as const,
    actionUrl: "/leave/requests/leave-2",
    metadata: {
      leaveRequestId: "leave-2",
      decision: "APPROVED",
    },
    sentAt: new Date("2025-01-10T16:15:00+06:00"),
  },
  {
    id: "notif-attendance-missed",
    organizationId: NDI_ORG_ID,
    senderId: "hr-arpon",
    title: "You missed your check-in",
    body: "No attendance was recorded for January 9. If you worked, please regularize the entry.",
    type: "ATTENDANCE" as const,
    audience: "INDIVIDUAL" as const,
    targetUserId: "emp-rafidul",
    status: "SENT" as const,
    actionUrl: "/attendance",
    metadata: {
      attendanceDate: "2025-01-09",
      shiftStart: "09:00",
    },
    sentAt: new Date("2025-01-09T18:00:00+06:00"),
  },
  {
    id: "notif-attendance-late",
    organizationId: NDI_ORG_ID,
    senderId: "hr-arpon",
    title: "Late check-in recorded",
    body: "You checked in at 10:12 AM today. Please try to be on time unless you are on remote schedule.",
    type: "ATTENDANCE" as const,
    audience: "INDIVIDUAL" as const,
    targetUserId: "emp-mueem",
    status: "SENT" as const,
    actionUrl: "/attendance",
    metadata: {
      attendanceDate: "2025-01-10",
      checkInAt: "10:12",
    },
    sentAt: new Date("2025-01-10T10:15:00+06:00"),
  },
  {
    id: "notif-report-daily-gap",
    organizationId: NDI_ORG_ID,
    senderId: "org-manager-tabuchi",
    title: "Daily report missing (Frontend)",
    body: "Two frontend engineers did not submit their daily report and were not on leave.",
    type: "REPORT" as const,
    audience: "ROLE" as const,
    targetRoles: ["HR_ADMIN", "ORG_ADMIN"] as UserRole[],
    status: "SENT" as const,
    actionUrl: "/hr-admin/reports/daily",
    metadata: {
      date: "2025-01-09",
      missingEmployees: ["emp-rafidul", "emp-mueem"],
    },
    sentAt: new Date("2025-01-09T22:00:00+06:00"),
  },
  {
    id: "notif-report-monthly-ready",
    organizationId: NDI_ORG_ID,
    senderId: "hr-yeasir",
    title: "Monthly report is ready",
    body: "The December monthly report has been compiled. Please review before sharing with leadership.",
    type: "REPORT" as const,
    audience: "ROLE" as const,
    targetRoles: ["HR_ADMIN", "ORG_ADMIN"] as UserRole[],
    status: "SENT" as const,
    actionUrl: "/hr-admin/reports/monthly",
    metadata: {
      reportMonth: "2024-12",
      ownerTeam: "People Ops",
    },
    sentAt: new Date("2025-01-11T09:00:00+06:00"),
  },
];

export const seedNotifications = async (prisma: PrismaClient) => {
  await prisma.notification.createMany({ data: notifications });
};
